[package]
name = "dwmstat-rs"
version = "0.1.0"
authors = ["Clemens Tiedt <clemens.tiedt@student.hpi.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"sysinfo" = "0.11.2"
"chrono" = "0.4.10"